### ISSUE TITLE
Getting gst1 driver to work

### ISSUE THREAD

**Issue by TheRealMarnes** [gstreamer-java/gst1-java-core#127]
I'm trying to set up the gst1 driver for a project on windows 10, and having mixed luck so far. The [older gstreamer doc](https://github.com/sarxos/webcam-capture/tree/master/webcam-capture-drivers/driver-gstreamer) refers to the [gst1 module](https://github.com/sarxos/webcam-capture/tree/master/webcam-capture-drivers/driver-gst1), which has no documentation. I'll gladly contribute a write-up for windows, if I can get this working, but I'm not familiar with gstreamer, jna, and everything else involved so far. Since you wrote this module, I assume you know your way around in all this stuff at least more than I do?

Situation so far:

- installed gstreamer 1.14.4 to `C:\Program Files (x86)\GStreamer` and added `C:\Program Files (x86)\GStreamer\1.0\x86_64\bin` to PATH
- downloaded webcam-capture 0.3.13-SNAPSHOT and `mvn package`d the gst1 module to a jar locally (since it doesn't seem to be on Central - am I missing something or is the gst1 module really still unreleased?)
- ClassDefNotFoundError made me check the gst1 module pom. I added gst1-java-core:0.9.0 and jna:4.2.2 to my dependencies, and an exclusion on webcam-capture for com.nativelibs4java, to mirror the gs1 module pom. Apparently maven doesn't properly apply poms from system jars...

Now when I call `Webcam.getDefault()` after installing `new Gst1Driver()`, I get this exception and I don't know what to make of it, seems like very internal stuff to me:

```
Caused by: com.github.sarxos.webcam.WebcamException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No such Gstreamer factory: ksvideosrc
	at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:124)
	at com.github.sarxos.webcam.Webcam.getWebcams(Webcam.java:893)
	at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:956)
	at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:933)
	at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:911)
	at net.leaumar.americam.PictureProviderSarxosNative.<init>(PictureProviderSarxosNative.java:31)
	at net.leaumar.americam.HttpServer.<clinit>(HttpServer.java:18)
	... 1 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No such Gstreamer factory: ksvideosrc
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:116)
	... 7 more
Caused by: java.lang.IllegalArgumentException: No such Gstreamer factory: ksvideosrc
	at org.freedesktop.gstreamer.ElementFactory.makeRawElement(ElementFactory.java:221)
	at org.freedesktop.gstreamer.ElementFactory.make(ElementFactory.java:91)
	at com.github.sarxos.webcam.ds.gst1.Gst1Driver.getDevices(Gst1Driver.java:71)
	at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:36)
	at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:26)
```

Could you help me get it working please? I'll write a setup guide for all this if we succeed.

**Comment by neilcsmith-net** [comment]
The library is published to Maven - see https://mvnrepository.com/artifact/org.freedesktop.gstreamer/gst1-java-core

Please update to 0.9.3 and JNA 4.5.1. This might break though as our API has changed. If you can still reproduce with current code please reopen.

**Comment by TheRealMarnes** [comment]
```
<dependency>
	<groupId>com.github.sarxos</groupId>
	<artifactId>webcam-capture-driver-gst1</artifactId>
	<version>0.3.13-SNAPSHOT</version>
</dependency>
<dependency>
	<groupId>org.freedesktop.gstreamer</groupId>
	<artifactId>gst1-java-core</artifactId>
	<version>0.9.3</version>
</dependency>
<dependency>
	<groupId>net.java.dev.jna</groupId>
	<artifactId>jna</artifactId>
	<version>4.5.1</version>
</dependency>
```

```
Caused by: com.github.sarxos.webcam.WebcamException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No such Gstreamer factory: ksvideosrc
	at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:124)
	at com.github.sarxos.webcam.Webcam.getWebcams(Webcam.java:893)
	at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:956)
	at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:933)
	at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:911)
	at net.leaumar.americam.PictureProvider.<init>(PictureProvider.java:31)
	at net.leaumar.americam.HttpServer.<clinit>(HttpServer.java:18)
	... 1 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No such Gstreamer factory: ksvideosrc
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:116)
	... 7 more
Caused by: java.lang.IllegalArgumentException: No such Gstreamer factory: ksvideosrc
	at org.freedesktop.gstreamer.ElementFactory.makeRawElement(ElementFactory.java:221)
	at org.freedesktop.gstreamer.ElementFactory.make(ElementFactory.java:91)
	at com.github.sarxos.webcam.ds.gst1.Gst1Driver.getDevices(Gst1Driver.java:71)
	at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:36)
	at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by TheRealMarnes** [comment]
@neilcsmith-net I can't reopen so I'm just calling out...

**Comment by neilcsmith-net** [comment]
Ok. Which install profile did you choose when installing GStreamer? If typical rather than full, try reinstalling everything. Camera support might be missing. 

Also check out the gst1-java-examples repo and try the simple webcam example there.

**Comment by TheRealMarnes** [comment]
The full shebang installed:

```
Caused by: com.github.sarxos.webcam.WebcamException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: Could not load library: gstinterfaces
	at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:124)
	at com.github.sarxos.webcam.Webcam.getWebcams(Webcam.java:893)
	at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:956)
	at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:933)
	at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:911)
	at net.leaumar.americam.PictureProvider.<init>(PictureProvider.java:31)
	at net.leaumar.americam.HttpServer.<clinit>(HttpServer.java:18)
	... 1 more
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: Could not load library: gstinterfaces
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:116)
	... 7 more
Caused by: java.lang.UnsatisfiedLinkError: Could not load library: gstinterfaces
	at org.freedesktop.gstreamer.lowlevel.GstNative.load(GstNative.java:56)
	at org.freedesktop.gstreamer.lowlevel.GstPropertyProbeAPI.<clinit>(GstPropertyProbeAPI.java:30)
	at org.freedesktop.gstreamer.interfaces.PropertyProbe.<init>(PropertyProbe.java:55)
	at org.freedesktop.gstreamer.interfaces.PropertyProbe.wrap(PropertyProbe.java:46)
	at com.github.sarxos.webcam.ds.gst1.Gst1Driver.getDevices(Gst1Driver.java:75)
	at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:36)
	at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
WARNING: no real random source present!
```

**Comment by TheRealMarnes** [comment]
The camera test in gst1-examples works fine

**Comment by neilcsmith-net** [comment]
OK, in that case please report to the sarxos webcam project or use this library directly - they're attempting to use functionality that doesn't exist in the GStreamer 1.x bindings. 

Thanks, Neil

**Comment by TheRealMarnes** [comment]
Oh, looks like I mixed up the project on which to post the issue :) I actually did mean to post it to sarxos, not gstreamer. My mistake, sorry

**Comment by TheRealMarnes** [comment]
Thanks for the help btw

**Comment by neilcsmith-net** [comment]
No problem! This project is neither btw. It's the binding in the middle so that Java applications can use GStreamer.
