### ISSUE TITLE
PlayBin.getVideoSinkFrameRate() UnsatisfiedLinkError

### ISSUE THREAD

**Issue by june5863** [gstreamer-java/gst1-java-core#98]
The gst_video_frame_rate defined in GstVideoAPI is unable to load.
GstVideoAPI  try to load native library, GstNative.load("gstvideo", GstVideoAPI.class) but failed.
I installed gstreamer 1.13 on Windows 7 and found libgstvideorate.dll instead of libgstvideo.dll.

The trace as follows;

Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: Error looking up function 'gst_video_frame_rate'

	at com.sun.jna.Function.<init>(Function.java:245)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:566)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:542)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:528)
	at com.sun.jna.Library$Handler.invoke(Library.java:228)
	at com.sun.proxy.$Proxy26.gst_video_frame_rate(Unknown Source)
	at org.freedesktop.gstreamer.Video.getVideoFrameRate(Video.java:22)
	at org.freedesktop.gstreamer.elements.PlayBin.getVideoSinkFrameRate(PlayBin.java:281)
	at net.aniot.cabincast.gstreamer.MediaPlayer.getFrameRate(MediaPlayer.java:236)
	at net.aniot.cabincast.gstreamer.PlayBinVideoPlayer.lambda$5(PlayBinVideoPlayer.java:141)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by neilcsmith-net** [comment]
Yes, sorry, this is a known issue.  I forgot to remove that method in the last release - it's carried forward from the 0.10 bindings but has never worked.

See a workaround at https://github.com/processing/processing-video/issues/71#issuecomment-341965361 Depends exactly what you're doing where the best place to get the Caps from is.

**Comment by june5863** [comment]
Thanks for quick response. I got the Fraction of framerate from AppSink.
